# coding: utf-8

"""
    Service-Oriented Vehicle Diagnostic API

    Definition of ASAM SOVD API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.entity_collection_entity_id_data_data_id_get200_response_errors_inner import EntityCollectionEntityIdDataDataIdGet200ResponseErrorsInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EntityCollectionEntityIdOperationsOperationIdExecutionsExecutionIdGet200Response(BaseModel):
    """
    EntityCollectionEntityIdOperationsOperationIdExecutionsExecutionIdGet200Response
    """ # noqa: E501
    status: Optional[StrictStr] = Field(default=None, description="Status of the executed operation.")
    capability: StrictStr = Field(description="Capability executed at the moment. This is either execute or the capability which has been used with a PUT request")
    parameters: Optional[Any] = Field(default=None, description="Additional OEM-specific information describing the environment of the system at the time of setting the fault. Condition: Only set if the fault provides the requested information.")
    schema_field: Optional[Dict[str, Any]] = Field(default=None, description="Placeholder schema definition. (External OpenAPI 3.1 schema reference removed for generator compatibility) ", alias="schema")
    error: Optional[List[EntityCollectionEntityIdDataDataIdGet200ResponseErrorsInner]] = Field(default=None, description="Condition: Set if an error occurred when the operation is executed. The path attribute references erroneous parameters of the operation execution. If the path attribute is “/” then the operation itself failed and the error describes the reason for the failure.")
    __properties: ClassVar[List[str]] = ["status", "capability", "parameters", "schema", "error"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('running', 'completed', 'failed'):
            raise ValueError("must be one of enum values ('running', 'completed', 'failed')")
        return value

    @field_validator('capability')
    def capability_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('execute', 'stop', 'freeze', 'reset', 'status'):
            raise ValueError("must be one of enum values ('execute', 'stop', 'freeze', 'reset', 'status')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EntityCollectionEntityIdOperationsOperationIdExecutionsExecutionIdGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in error (list)
        _items = []
        if self.error:
            for _item in self.error:
                if _item:
                    _items.append(_item.to_dict())
            _dict['error'] = _items
        # set to None if parameters (nullable) is None
        # and model_fields_set contains the field
        if self.parameters is None and "parameters" in self.model_fields_set:
            _dict['parameters'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EntityCollectionEntityIdOperationsOperationIdExecutionsExecutionIdGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "capability": obj.get("capability"),
            "parameters": obj.get("parameters"),
            "schema": obj.get("schema"),
            "error": [EntityCollectionEntityIdDataDataIdGet200ResponseErrorsInner.from_dict(_item) for _item in obj.get("error")] if obj.get("error") is not None else None
        })
        return _obj


