# coding: utf-8

"""
    Service-Oriented Vehicle Diagnostic API

    Definition of ASAM SOVD API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.entity_collection_entity_id_operations_operation_id_executions_post200_response_error import EntityCollectionEntityIdOperationsOperationIdExecutionsPost200ResponseError
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EntityCollectionEntityIdUpdatesUpdatePackageIdStatusGet200ResponseSubprogressInner(BaseModel):
    """
    EntityCollectionEntityIdUpdatesUpdatePackageIdStatusGet200ResponseSubprogressInner
    """ # noqa: E501
    entity: StrictStr = Field(description="URI of the entity.")
    status: StrictStr = Field(description="Status of the preparation or execution.")
    progress: Optional[StrictInt] = Field(default=None, description="Progress of the preparation or execution in percent.")
    error: Optional[EntityCollectionEntityIdOperationsOperationIdExecutionsPost200ResponseError] = None
    __properties: ClassVar[List[str]] = ["entity", "status", "progress", "error"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('pending', 'inProgress', 'failed', 'completed'):
            raise ValueError("must be one of enum values ('pending', 'inProgress', 'failed', 'completed')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EntityCollectionEntityIdUpdatesUpdatePackageIdStatusGet200ResponseSubprogressInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EntityCollectionEntityIdUpdatesUpdatePackageIdStatusGet200ResponseSubprogressInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "entity": obj.get("entity"),
            "status": obj.get("status"),
            "progress": obj.get("progress"),
            "error": EntityCollectionEntityIdOperationsOperationIdExecutionsPost200ResponseError.from_dict(obj.get("error")) if obj.get("error") is not None else None
        })
        return _obj


