# coding: utf-8

"""
    Service-Oriented Vehicle Diagnostic API

    Definition of ASAM SOVD API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401



from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, ValidationError, field_validator
from typing import Any, Dict, List, Optional, Union
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

ENTITYCOLLECTIONENTITYIDOPERATIONSOPERATIONIDGET200RESPONSEMODESVALUE_ANY_OF_SCHEMAS = ["List[object]", "bool", "float", "int", "object", "str"]

class EntityCollectionEntityIdOperationsOperationIdGet200ResponseModesValue(BaseModel):
    """
    Additional OEM-specific information describing the environment of the system at the time of setting the fault. Condition: Only set if the fault provides the requested information.
    """

    # data type: str
    anyofschema_field_1_validator: Optional[StrictStr] = None
    # data type: float
    anyofschema_field_2_validator: Optional[Union[StrictFloat, StrictInt]] = None
    # data type: int
    anyofschema_field_3_validator: Optional[StrictInt] = None
    # data type: bool
    anyofschema_field_4_validator: Optional[StrictBool] = None
    # data type: List[object]
    anyofschema_field_5_validator: Optional[List[Any]] = None
    # data type: object
    anyofschema_field_6_validator: Optional[Dict[str, Any]] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[List[object], bool, float, int, object, str]] = None
    else:
        actual_instance: Any = None
    any_ofschema_fields: List[str] = Literal[ENTITYCOLLECTIONENTITYIDOPERATIONSOPERATIONIDGET200RESPONSEMODESVALUE_ANY_OF_SCHEMAS]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = EntityCollectionEntityIdOperationsOperationIdGet200ResponseModesValue.model_construct()
        error_messages = []
        # validate data type: str
        try:
            instance.anyofschema_field_1_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: float
        try:
            instance.anyofschema_field_2_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: int
        try:
            instance.anyofschema_field_3_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: bool
        try:
            instance.anyofschema_field_4_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: List[object]
        try:
            instance.anyofschema_field_5_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: object
        try:
            instance.anyofschema_field_6_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in EntityCollectionEntityIdOperationsOperationIdGet200ResponseModesValue with anyOf schemas: List[object], bool, float, int, object, str. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # deserialize data into str
        try:
            # validation
            instance.anyofschema_field_1_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyofschema_field_1_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into float
        try:
            # validation
            instance.anyofschema_field_2_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyofschema_field_2_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into int
        try:
            # validation
            instance.anyofschema_field_3_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyofschema_field_3_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into bool
        try:
            # validation
            instance.anyofschema_field_4_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyofschema_field_4_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into List[object]
        try:
            # validation
            instance.anyofschema_field_5_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyofschema_field_5_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into object
        try:
            # validation
            instance.anyofschema_field_6_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyofschema_field_6_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into EntityCollectionEntityIdOperationsOperationIdGet200ResponseModesValue with anyOf schemas: List[object], bool, float, int, object, str. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_dict()
        else:
            return json.dumps(self.actual_instance)

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


