# coding: utf-8

"""
    Service-Oriented Vehicle Diagnostic API

    Definition of ASAM SOVD API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EntityCollectionEntityIdConfigurationsGet200ResponseItemsInner(BaseModel):
    """
    EntityCollectionEntityIdConfigurationsGet200ResponseItemsInner
    """ # noqa: E501
    id: StrictStr = Field(description="Unique identifier of a configuration data")
    name: StrictStr = Field(description="Name of the configuration data")
    translation_id: Optional[StrictStr] = Field(default=None, description="Identifier for translating the configurations data name")
    type: StrictStr = Field(description="Configuration type definition")
    version: Optional[StrictStr] = Field(default=None, description="Version of the configuration data. version and content_type are mandatory for bulk data configurations but are not present for parameter-based configurations.")
    content_type: Optional[StrictStr] = Field(default=None, description="MIME type with information for the SOVD client about the content type, e.g., XML etc. version and content_type are mandatory for bulk data configurations but are not present for parameter-based configurations.")
    __properties: ClassVar[List[str]] = ["id", "name", "translation_id", "type", "version", "content_type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('bulk', 'parameter'):
            raise ValueError("must be one of enum values ('bulk', 'parameter')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EntityCollectionEntityIdConfigurationsGet200ResponseItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EntityCollectionEntityIdConfigurationsGet200ResponseItemsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "translation_id": obj.get("translation_id"),
            "type": obj.get("type"),
            "version": obj.get("version"),
            "content_type": obj.get("content_type")
        })
        return _obj


