# coding: utf-8

"""
    Service-Oriented Vehicle Diagnostic API

    Definition of ASAM SOVD API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.entity_collection_entity_id_updates_get_origin_parameter import EntityCollectionEntityIdUpdatesGetOriginParameter
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EntityCollectionEntityIdUpdatesUpdatePackageIdGet200Response(BaseModel):
    """
    EntityCollectionEntityIdUpdatesUpdatePackageIdGet200Response
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Identifier of the update package. Condition: Only provided if the path parameter update-package-id autonomous was used.")
    update_name: StrictStr = Field(description="Name of the update")
    automated: Optional[StrictBool] = Field(default=None, description="Specifies whether the update package can be installed automatedly or not. If missing, the attribute defaults to false.")
    origin: Optional[List[EntityCollectionEntityIdUpdatesGetOriginParameter]] = Field(default=None, description="List of origins for which the update package is applicable. If the attribute is left out or empty, any origin is applicable.")
    update_translation_id: Optional[StrictStr] = Field(default=None, description="Translation identifier for the update_name.")
    notes: Optional[StrictStr] = Field(default=None, description="Release notes for the updates, may also be a URI.")
    notes_translation_id: Optional[StrictStr] = Field(default=None, description="Translation identifier for the notes.")
    user_activity: Optional[StrictStr] = Field(default=None, description="Activities which have to be performed by the user after the update.")
    user_activity_translation_id: Optional[StrictStr] = Field(default=None, description="Translation identifier for the user_activity.")
    preconditions: Optional[StrictStr] = Field(default=None, description="Preconditions which shall be fulfilled for installing the update (e.g., doors locked, parking, …). In general, not being able to fulfill the preconditions would block the preparation of the update.")
    preconditions_transaltion_id: Optional[StrictStr] = Field(default=None, description="Translation identifier for the preconditions.")
    execution_conditions: Optional[StrictStr] = Field(default=None, description="Description of the conditions which are required for executing the update. May only be set if status is completed.")
    duration: Optional[StrictInt] = Field(default=None, description="Time for which the vehicle will not be available when the update is installed and activated. The time is defined in seconds. If not set, the availability of the vehicle would not be affected.")
    size: StrictInt = Field(description="The download size of the update. The size is defined in kilo bytes.")
    updated_components: Optional[List[StrictStr]] = Field(default=None, description="A list of Components to be updated. The URIs are in the form of {entity-path}.")
    affected_components: Optional[List[StrictStr]] = Field(default=None, description="The list documents which Components may have a different behavior etc. The focus lies on user-perceived functions and Components. The URIs are in the form of {entity-path}.")
    schema_field: Optional[Dict[str, Any]] = Field(default=None, description="Placeholder schema definition. (External OpenAPI 3.1 schema reference removed for generator compatibility) ", alias="schema")
    __properties: ClassVar[List[str]] = ["id", "update_name", "automated", "origin", "update_translation_id", "notes", "notes_translation_id", "user_activity", "user_activity_translation_id", "preconditions", "preconditions_transaltion_id", "execution_conditions", "duration", "size", "updated_components", "affected_components", "schema"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EntityCollectionEntityIdUpdatesUpdatePackageIdGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in origin (list)
        _items = []
        if self.origin:
            for _item in self.origin:
                if _item:
                    _items.append(_item.to_dict())
            _dict['origin'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EntityCollectionEntityIdUpdatesUpdatePackageIdGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "update_name": obj.get("update_name"),
            "automated": obj.get("automated"),
            "origin": [EntityCollectionEntityIdUpdatesGetOriginParameter.from_dict(_item) for _item in obj.get("origin")] if obj.get("origin") is not None else None,
            "update_translation_id": obj.get("update_translation_id"),
            "notes": obj.get("notes"),
            "notes_translation_id": obj.get("notes_translation_id"),
            "user_activity": obj.get("user_activity"),
            "user_activity_translation_id": obj.get("user_activity_translation_id"),
            "preconditions": obj.get("preconditions"),
            "preconditions_transaltion_id": obj.get("preconditions_transaltion_id"),
            "execution_conditions": obj.get("execution_conditions"),
            "duration": obj.get("duration"),
            "size": obj.get("size"),
            "updated_components": obj.get("updated_components"),
            "affected_components": obj.get("affected_components"),
            "schema": obj.get("schema")
        })
        return _obj


