# coding: utf-8

"""
    Service-Oriented Vehicle Diagnostic API

    Definition of ASAM SOVD API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EntityCollectionEntityIdGet200Response(BaseModel):
    """
    EntityCollectionEntityIdGet200Response
    """ # noqa: E501
    id: StrictStr = Field(description="Entity-Id")
    name: StrictStr = Field(description="Name of the Entity")
    translation_id: Optional[StrictStr] = Field(default=None, description="Identifier for translating the name")
    variant: Optional[Any] = Field(default=None, description="Additional OEM-specific information describing the environment of the system at the time of setting the fault. Condition: Only set if the fault provides the requested information.")
    configurations: Optional[StrictStr] = Field(default=None, description="A reference to the configurations collection")
    bulk_data: Optional[StrictStr] = Field(default=None, description="A reference to the bulk-data collection", alias="bulk-data")
    data: Optional[StrictStr] = Field(default=None, description="A reference to the data collection")
    data_lists: Optional[StrictStr] = Field(default=None, description="A reference to the data-lists collection", alias="data-lists")
    faults: Optional[StrictStr] = Field(default=None, description="A reference to faults collection")
    operations: Optional[StrictStr] = Field(default=None, description="A reference to the operations collections")
    updates: Optional[StrictStr] = Field(default=None, description="A reference to the updated collection")
    modes: Optional[StrictStr] = Field(default=None, description="A reference tot the modes collection")
    relatedapps: Optional[StrictStr] = Field(default=None, description="A reference to the reference-collection providing the apps (Only available for components)")
    relatedcomponents: Optional[StrictStr] = Field(default=None, description="A reference to the reference-collection providing the components (Only available for areas)")
    subareas: Optional[StrictStr] = Field(default=None, description="A reference to the reference-collection providing the subareas (Only available for areas)")
    subcomponents: Optional[StrictStr] = Field(default=None, description="A reference to the reference-collection providing the subcomponents (Only available for components)")
    locks: Optional[StrictStr] = Field(default=None, description="A reference to the reference-collection locks")
    logs: Optional[StrictStr] = Field(default=None, description="A reference to the resource logs")
    __properties: ClassVar[List[str]] = ["id", "name", "translation_id", "variant", "configurations", "bulk-data", "data", "data-lists", "faults", "operations", "updates", "modes", "relatedapps", "relatedcomponents", "subareas", "subcomponents", "locks", "logs"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EntityCollectionEntityIdGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if variant (nullable) is None
        # and model_fields_set contains the field
        if self.variant is None and "variant" in self.model_fields_set:
            _dict['variant'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EntityCollectionEntityIdGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "translation_id": obj.get("translation_id"),
            "variant": obj.get("variant"),
            "configurations": obj.get("configurations"),
            "bulk-data": obj.get("bulk-data"),
            "data": obj.get("data"),
            "data-lists": obj.get("data-lists"),
            "faults": obj.get("faults"),
            "operations": obj.get("operations"),
            "updates": obj.get("updates"),
            "modes": obj.get("modes"),
            "relatedapps": obj.get("relatedapps"),
            "relatedcomponents": obj.get("relatedcomponents"),
            "subareas": obj.get("subareas"),
            "subcomponents": obj.get("subcomponents"),
            "locks": obj.get("locks"),
            "logs": obj.get("logs")
        })
        return _obj


