# coding: utf-8

"""
    Service-Oriented Vehicle Diagnostic API

    Definition of ASAM SOVD API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.entity_collection_entity_id_operations_operation_id_executions_post200_response_error import EntityCollectionEntityIdOperationsOperationIdExecutionsPost200ResponseError
from openapi_server.models.entity_collection_entity_id_updates_update_package_id_status_get200_response_subprogress_inner import EntityCollectionEntityIdUpdatesUpdatePackageIdStatusGet200ResponseSubprogressInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EntityCollectionEntityIdUpdatesUpdatePackageIdStatusGet200Response(BaseModel):
    """
    EntityCollectionEntityIdUpdatesUpdatePackageIdStatusGet200Response
    """ # noqa: E501
    phase: StrictStr = Field(description="Current phase of the update process.")
    status: StrictStr = Field(description="Status of the preparation or execution.")
    progress: Optional[StrictInt] = Field(default=None, description="Progress of the preparation or execution in percent.")
    subprogress: Optional[List[EntityCollectionEntityIdUpdatesUpdatePackageIdStatusGet200ResponseSubprogressInner]] = Field(default=None, description="Progress of the updated entities.")
    step: Optional[StrictStr] = Field(default=None, description="Description of the current step.")
    step_translation_id: Optional[StrictStr] = Field(default=None, description="Translation identifier for the step.")
    error: Optional[EntityCollectionEntityIdOperationsOperationIdExecutionsPost200ResponseError] = None
    __properties: ClassVar[List[str]] = ["phase", "status", "progress", "subprogress", "step", "step_translation_id", "error"]

    @field_validator('phase')
    def phase_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('prepare', 'execute'):
            raise ValueError("must be one of enum values ('prepare', 'execute')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('pending', 'inProgress', 'failed', 'completed'):
            raise ValueError("must be one of enum values ('pending', 'inProgress', 'failed', 'completed')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EntityCollectionEntityIdUpdatesUpdatePackageIdStatusGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in subprogress (list)
        _items = []
        if self.subprogress:
            for _item in self.subprogress:
                if _item:
                    _items.append(_item.to_dict())
            _dict['subprogress'] = _items
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EntityCollectionEntityIdUpdatesUpdatePackageIdStatusGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "phase": obj.get("phase"),
            "status": obj.get("status"),
            "progress": obj.get("progress"),
            "subprogress": [EntityCollectionEntityIdUpdatesUpdatePackageIdStatusGet200ResponseSubprogressInner.from_dict(_item) for _item in obj.get("subprogress")] if obj.get("subprogress") is not None else None,
            "step": obj.get("step"),
            "step_translation_id": obj.get("step_translation_id"),
            "error": EntityCollectionEntityIdOperationsOperationIdExecutionsPost200ResponseError.from_dict(obj.get("error")) if obj.get("error") is not None else None
        })
        return _obj


