# coding: utf-8

"""
    Service-Oriented Vehicle Diagnostic API

    Definition of ASAM SOVD API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EntityCollectionEntityIdOperationsGet200ResponseItemsInner(BaseModel):
    """
    EntityCollectionEntityIdOperationsGet200ResponseItemsInner
    """ # noqa: E501
    id: StrictStr = Field(description="Unique identifier for an operation")
    name: Optional[StrictStr] = Field(default=None, description="Operation name")
    translation_id: Optional[StrictStr] = Field(default=None, description="Identifier for translating the operations name")
    proximity_proof_required: StrictBool = Field(description="If true, the execution of the operation requires a proof of proximity. An SOVD client can use this information to filter operations in advance if a proximity proof cannot be provided. If true, the offline Capability description includes the attribute x-sovd-proximity-proof-required in the PathItem object.")
    asynchronous_execution: StrictBool = Field(description="If true, the execution of the operation is asynchronous. If true, the offline Capability description includes the attribute x-sovd-asynchronous-execution with the value true in the PathItem object.")
    __properties: ClassVar[List[str]] = ["id", "name", "translation_id", "proximity_proof_required", "asynchronous_execution"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EntityCollectionEntityIdOperationsGet200ResponseItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EntityCollectionEntityIdOperationsGet200ResponseItemsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "translation_id": obj.get("translation_id"),
            "proximity_proof_required": obj.get("proximity_proof_required"),
            "asynchronous_execution": obj.get("asynchronous_execution")
        })
        return _obj


