# coding: utf-8

"""
    Service-Oriented Vehicle Diagnostic API

    Definition of ASAM SOVD API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.entity_collection_entity_id_logs_entries_get200_response_items_inner_context import EntityCollectionEntityIdLogsEntriesGet200ResponseItemsInnerContext
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EntityCollectionEntityIdLogsEntriesGet200ResponseItemsInner(BaseModel):
    """
    EntityCollectionEntityIdLogsEntriesGet200ResponseItemsInner
    """ # noqa: E501
    timestamp: datetime = Field(description="Format: RFC3339 (UTC)")
    context: EntityCollectionEntityIdLogsEntriesGet200ResponseItemsInnerContext
    severity: StrictStr = Field(description="The severity specifies the log-level for the given context.")
    msg: StrictStr = Field(description="The actual log message (text)")
    href: Optional[StrictStr] = Field(default=None, description="Reference to a URI for retrieving the underlying original log file in an application specific format")
    __properties: ClassVar[List[str]] = ["timestamp", "context", "severity", "msg", "href"]

    @field_validator('severity')
    def severity_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('fatal', 'error', 'warn', 'info', 'debug'):
            raise ValueError("must be one of enum values ('fatal', 'error', 'warn', 'info', 'debug')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EntityCollectionEntityIdLogsEntriesGet200ResponseItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of context
        if self.context:
            _dict['context'] = self.context.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EntityCollectionEntityIdLogsEntriesGet200ResponseItemsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "timestamp": obj.get("timestamp"),
            "context": EntityCollectionEntityIdLogsEntriesGet200ResponseItemsInnerContext.from_dict(obj.get("context")) if obj.get("context") is not None else None,
            "severity": obj.get("severity"),
            "msg": obj.get("msg"),
            "href": obj.get("href")
        })
        return _obj


