# coding: utf-8

"""
    Service-Oriented Vehicle Diagnostic API

    Definition of ASAM SOVD API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.entity_collection_entity_id_configurations_get200_response_items_inner import EntityCollectionEntityIdConfigurationsGet200ResponseItemsInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EntityCollectionEntityIdConfigurationsGet200Response(BaseModel):
    """
    EntityCollectionEntityIdConfigurationsGet200Response
    """ # noqa: E501
    items: List[EntityCollectionEntityIdConfigurationsGet200ResponseItemsInner] = Field(description="The list of all configurations provided by the entity.")
    schema_field: Optional[Dict[str, Any]] = Field(default=None, description="Placeholder schema definition. (External OpenAPI 3.1 schema reference removed for generator compatibility) ", alias="schema")
    __properties: ClassVar[List[str]] = ["items", "schema"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EntityCollectionEntityIdConfigurationsGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item in self.items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EntityCollectionEntityIdConfigurationsGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "items": [EntityCollectionEntityIdConfigurationsGet200ResponseItemsInner.from_dict(_item) for _item in obj.get("items")] if obj.get("items") is not None else None,
            "schema": obj.get("schema")
        })
        return _obj


