# coding: utf-8

"""
    Service-Oriented Vehicle Diagnostic API

    Definition of ASAM SOVD API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EntityCollectionEntityIdOperationsOperationIdExecutionsExecutionIdPutRequest(BaseModel):
    """
    EntityCollectionEntityIdOperationsOperationIdExecutionsExecutionIdPutRequest
    """ # noqa: E501
    capability: StrictStr = Field(description="Capability to be executed (one of execute, freeze, or reset as well as the OEM specific capabilities.")
    timeout: Optional[StrictInt] = Field(default=None, description="Timeout after which the SOVD server should terminate the execution of the operation by using the capability stop. The time is specified in seconds. For extending the timeout a new control request for the operation has to be submitted by the SOVD client.")
    parameters: Optional[Any] = Field(default=None, description="Parameters for executing the operation.")
    proximity_response: Optional[StrictStr] = Field(default=None, description="Response to proximity challenge if required by the operation.")
    __properties: ClassVar[List[str]] = ["capability", "timeout", "parameters", "proximity_response"]

    @field_validator('capability')
    def capability_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('execute', 'stop', 'freeze', 'reset', 'status'):
            raise ValueError("must be one of enum values ('execute', 'stop', 'freeze', 'reset', 'status')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EntityCollectionEntityIdOperationsOperationIdExecutionsExecutionIdPutRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if parameters (nullable) is None
        # and model_fields_set contains the field
        if self.parameters is None and "parameters" in self.model_fields_set:
            _dict['parameters'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EntityCollectionEntityIdOperationsOperationIdExecutionsExecutionIdPutRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "capability": obj.get("capability"),
            "timeout": obj.get("timeout"),
            "parameters": obj.get("parameters"),
            "proximity_response": obj.get("proximity_response")
        })
        return _obj


