# coding: utf-8

"""
    Service-Oriented Vehicle Diagnostic API

    Definition of ASAM SOVD API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EntityCollectionEntityIdDataDataIdGet200ResponseErrorsInnerError(BaseModel):
    """
    Describes the error more precisely. Condition: The attribute referenced by path contains an error.
    """ # noqa: E501
    error_code: StrictStr = Field(description="SOVD standardized error code")
    vendor_code: Optional[StrictStr] = Field(default=None, description="Vendor specific error code Condition: If the error_code is vendor-specific this attribute has to be filled.")
    message: StrictStr = Field(description="Message describing the problem in more detail.")
    translation_id: Optional[StrictStr] = Field(default=None, description="Identifier for translating the message")
    parameters: Optional[Dict[str, Any]] = Field(default=None, description="Key-value-list which provides additional information on the error")
    __properties: ClassVar[List[str]] = ["error_code", "vendor_code", "message", "translation_id", "parameters"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EntityCollectionEntityIdDataDataIdGet200ResponseErrorsInnerError from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EntityCollectionEntityIdDataDataIdGet200ResponseErrorsInnerError from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "error_code": obj.get("error_code"),
            "vendor_code": obj.get("vendor_code"),
            "message": obj.get("message"),
            "translation_id": obj.get("translation_id"),
            "parameters": obj.get("parameters")
        })
        return _obj


